### ISSUE TITLE
Creating single-page-apps

### ISSUE THREAD

**Issue by silentninja** [stowball/quench-vue#5]
Is it possible to create single page apps with nested routes using this method. It would be really awesome if it is possible.
Thanks a lot for creating this library!!!

**Comment by stowball** [comment]
What's the use-case? If you're doing an SPA, why not use use "proper" Vue all done in JS (like with vue-cli)?

**Comment by silentninja** [comment]
Seo is the problem with SPA's. We could use proper ssr but if I am using a different language other than nodejs, there is a hassle of running a extra node server.

**Comment by stowball** [comment]
There's no reason why you can't pre-render the entire page with a Quenched `<div id="app"></div>`and then let the SPA JS take over and do the rest. You'd just need to pass the original route etc in `q-data`

**Comment by silentninja** [comment]
Tried using vue router,dynamic components and it works fine, but the workflow becomes difficult. The problem i faced was with storing data in vuex and routing in the case of nested routes. Flat routes worked well without problem.
 I ended up using it without SPA, works great so far.
