### ISSUE TITLE
Snapshot, then bootstrap from client-side Vue-generated html?

### ISSUE THREAD

**Issue by fzembow** [stowball/quench-vue#6]
Hi @stowball! Great project, was just looking for something like this :)

Here's a workflow I am trying to support. I like to build single pages using Vue in its entirety, as I find the component hierarchy and everything else very easy to use, and would like to layer in some interactivity (think, for example, an article that is mostly text and images but has some interaction around charts and data built in).

But for production, I want the rendered page to bootstrap from the Vue-rendered html for SEO and time-to-load purposes, and I don't want to set up true server-side rendering for a single page. But from playing with `quench-vue` seems to require manual coding of specially constructed html to work, and it feels somewhat tedious to have to use the html as the source of truth for data, templates, and components, or split between the two.

I was wondering if you've thought about some kind of workflow where you do everything in `.vue` files (specifically, a project created using vue-cli), and then:

1. Snapshot (within the browser, or using something like phantom-js), the rendered Vue app. Might make sense to do this as a build step.
2. Output that as the `index.html` for the production vue app. This should mean that loading index.html even without js enabled would result in the same rendered DOM but without any interactivity.
3. When instantiating the vue app itself, it would either replace the contents of `<div id="app">` (like happens by default) or (ideally) reuse the existing DOM that exists after the rendering of the static content. (not sure of this last one since that 

Does this idea make sense? Is this something `quench-vue` aims to support? Or is that somewhat of an orthogonal project in your mind? I think it's like a mix between https://github.com/bahmutov/hydrate-app and this. Very interested in this concept, would be happy to contribute. cc @bahmutov

Also FYI the project logo on the README is a 404 now it seems :(

Cheers,
f

**Comment by fzembow** [comment]
After some more digging I found https://www.npmjs.com/package/prerender-spa-plugin which does this as a webpack plugin. Carry on :)

**Comment by stowball** [comment]
Oh nice. I'll check that plugin out
