### ISSUE TITLE
Any way to bind data without an element?

### ISSUE THREAD

**Issue by faelsoto** [stowball/quench-vue#7]
Hey, I just found this library and it's pretty cool, thanks for that.

I've read the whole documentation, but haven't found a way to reference one object's property to the data, without creating an HTML element. If we have a set of skills:

```html
<div id="app" q-convert-bindings>
  <li v-for="skill in skills">
    <span q-binding="skills[0].name as skill.name">JS</span>
    <span q-binding="skills[0].level as skill.level">4</span>
  </li>
  <!-- <q> -->
  <li>
    <span q-binding="skills[1].name as skill.name">CSS</span>
    <span q-binding="skills[1].level as skill.level">5</span>
  </li>
  <!-- </q> -->
</div>
```

What would be the way to create a property for each `<li>` that references the skill ID given in database? Is it possible?

**Comment by stowball** [comment]
I'm not sure I fully understand, but are you asking how you can set the Vue app's `data` without writing the HTML? If you already have the data available from the server, don't use `q-convert-bindings` and instead set the `q-data` with stringified JSON:

```html
<div id="app" q-data='{
  "skills": [
    {
      "name": "JS",
      "level": 4
    },
    {
      "name": "CSS",
      "level": 5
    }
  ]
}'>
…
</div>
```

This will make the `skills` array available for you to use within your app.

In your above example, you could also replace every element with a `<template>` tag, which would set  the data from the HTML while not rendering anything. Does that help?

**Comment by faelsoto** [comment]
Thanks for replying. What I'm referring to is what happens if my model has 3 attributes (id, name, level), but only two are rendered in the HTML (name and level), is there a way to set a hidden `data-id` within the `<li>`?

```html
<div id="app" q-convert-bindings>
  <li v-for="skill in skills" data-id="1">
    <span q-binding="skills[0].name as skill.name">JS</span>
    <span q-binding="skills[0].level as skill.level">4</span>
  </li>
  <!-- <q> -->
  <li data-id="2">
    <span q-binding="skills[1].name as skill.name">CSS</span>
    <span q-binding="skills[1].level as skill.level">5</span>
  </li>
  <!-- </q> -->
</div>
```

This way the data structure would end up being

```
{
  "skills": [
    {
      "id": 1,
      "name": "JS",
      "level": 4
    },
    {
      "id": 2,
      "name": "CSS",
      "level": 5
    }
  ]
}
```

The `<template>` tag might be helpful, but what I'm working with is a table, so any «foreign» HTML might destroy it.

Also, the `q-data` option is discarded for our use case because we have too much rendered data and we'd like to preserve it.

**Comment by stowball** [comment]
I just tried using `<template>` and unfortunately it doesn't work. Let me think about this a little more and see if I can implement a solution for you.

Out of interest, why is using `q-data` a no go? If you already render the data in the markup, can you also not render it as stringified JSON (which is what I do in my job)?

**Comment by faelsoto** [comment]
We want to hydrate one table that has multiple variants: on one column we might show a small number depending on a setting, the currency symbols are rendered server-side and it could be very troublesome to create another parser and renderer for js while we all need within this table is to be able to select multiple rows so we could perform an action on these rows.

I opened this issue just to see if we were missing something from the docs. Another thing we might need is to keep the innerHTML info rather than the textContent info, so we might create a PR.

Another thing we're evaluating is parsing the HTML table for each element we need and store it in an array and then create the Vue element, but quench looks actually like something that's not so hacky.

**Comment by stowball** [comment]
Hey @faelsoto. Can you try this branch out to see if it suits your needs https://github.com/stowball/quench-vue/tree/feature/comment-q-bindings?

It allows you create `data` properties through HTML comments:

```
<!-- q-binding="foo = str" -->
<!-- q-binding="bar[0] = true" -->
<!-- q-binding="baz.qux = 1" -->
<!-- q-binding="corge[0].uier = 'str-quotes-optional'" -->
``` 

I've also fixed it so numbers and booleans are correctly converted from strings when using `q-binding`

**Comment by faelsoto** [comment]
Thanks, I'll check it through the day.

**Comment by stowball** [comment]
Hey. Did you manage to test this out?

**Comment by stowball** [comment]
@faelsoto Not sure if you're still interested, but it turns out that I had a need for it as well, so have just published an improved version of my initial branch as 0.7.0
